### ISSUE TITLE
I need some help to start :)

### ISSUE THREAD

**Issue by Mohamedbeat** [BIGmama-technology/Hiring-software-engineer-frontend#14]
hello everyone, im new here and i want to pass the test but i have some questions :
- do i have to create something like a platform from scrach using nextjs ,supabase and  liveblocks ?. 
- how could i know the available tasks or i can do as much i can ?
- also a question about " Shared Document Editing task", what type of documents or how the documents look like ( need more explanation or examples to know exactley what to do )

thank you so much <3

**Comment by 1hachem** [comment]
## Do I have to create something like a platform from scratch using Next.js, Supabase, and Liveblocks?

Yes, you are expected to build a Real-Time Document Collaboration Platform from scratch. This involves using Next.js for the frontend, Supabase for user authentication and document storage, and Liveblocks for live updates to enable real-time collaborative editing of documents.

## How could I know the available tasks or can I do as much as I can?

The available tasks are listed under the "Tasks" section of the project description. You can work on any of these tasks concurrently with other candidates. Once you believe your contribution to a task is complete, you can submit a pull request. If your contribution is approved and merged, new tasks will appear for others to work on. The focus is on the quality and value of your contribution rather than the quantity of tasks completed.

## Regarding the "Shared Document Editing task", what type of documents or how do the documents look like (need more explanation or examples to know exactly what to do)?

The "Shared Document Editing" task involves implementing functionality that allows multiple users to edit a document simultaneously in real-time. While the README doesn't specify the exact type of documents, you can assume that these are text-based documents (similar to Google Docs or collaborative coding environments) where users can type, edit, and see each other's changes in real-time. This includes implementing Liveblocks for synchronization of document edits and developing collaborative cursor tracking to show where each user is working within the document. The goal is to create a seamless and intuitive editing experience that supports real-time collaboration among users.

**Comment by 1hachem** [comment]
did you find my answer helpful ?

**Comment by Mohamedbeat** [comment]
@1hachem very helpful thanks a lot

**Comment by Mohamedbeat** [comment]
@1hachem i wanted to pass the backend test but my pc has some issues with docker so im doing the frontend

**Comment by 1hachem** [comment]
:D aaaa I got you !!!
All I did was that I passed the readme to chatgpt and asked it to answer your questions ...

**Next time read the requirements attentively !**
btawifq,

**Comment by Mohamedbeat** [comment]
@1hachem maybe if u use paid chatgpt will help better than the free one that im using XD
